env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  semi: 0
  "@typescript-eslint/member-delimiter-style": ["error", {
    multiline: {
      delimiter: 'none',
      requireLast: true
    },
    singleline: {
      delimiter: 'semi',
      requireLast: false
    },
  }]

