---
# prepare system and update packages
- name: Update apt & cache
  become: true
  apt:
    upgrade: 'yes'
    update_cache: 'yes'
    force_apt_get: true
    cache_valid_time: 36000

- name: Install system package dependencies
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    force_apt_get: true

- name: Upgrade pip core packages
  pip:
    name: "{{ pip_core }}"
    state: latest

- name: Install Python core requirements
  pip:
    name: "{{ python_core }}"
    state: present

# See: https://github.com/npm/cli/issues/681
- name: Install NPM manually since default installation is outdated
  become: yes
  shell: >
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash
  ignore_errors: no
  args:
    warn: false

- name: Install NodeJS system dependencies
  become: true
  apt:
    name: "{{ nodejs_core }}"
    state: latest
    update_cache: yes
    force_apt_get: true
